create table tareas (id bigint generated by default as identity, external_id varchar(255), name varchar(255),created_at timestamp, modified_at timestamp, primary key (id),
constraint tareas_external_id_unique unique (external_id));
create table usuarios (id bigint generated by default as identity, password varchar(255), username varchar(255), created_at timestamp, modified_at timestamp, primary key (id));
create table estados_tarea (id bigint generated by default as identity, task_id bigint, state varchar(255), external_id varchar(255),created_at timestamp, modified_at timestamp,
                            primary key (id),
                            foreign key (task_id) references tareas(id),
                            constraint estados_tarea_external_id_unique unique (external_id));
create index task_external_id_index on tareas (external_id);
create index task_state_external_id_index on estados_tarea (external_id);
